name: 'Stop Windows Performance Trace Recording'
description: 'An action that simplifies recording Windows performance traces using Windows Performance Recorder'
author: "chad-golden"
branding:
  icon: play-circle
  color: gray-dark
inputs:
  trace-file-name:
    type: string
    description: 'The file name the trace will be written to, default is trace.etl'
    default: trace.etl
runs:
  using: 'composite'
  steps:
    - shell: pwsh
      env:
        TRACE_FILE_NAME: ${{ inputs.trace-file-name }}
      run: ${{ github.action_path }}/../scripts/stop.ps1