name: Tests

on:
  push:
    branches: [main]
    paths:
      - '**/test.yml'
      - 'scripts/**'
      - '**action.yml'
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - windows-2019
          - windows-2022
          - windows-2025
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Windows Performance Recorder
      uses: ./

    - name: Ensure wpr.exe
      run: wpr.exe -help

    - name: Start trace
      uses: ./start

    - name: Stop trace
      uses: ./stop
      with:
        trace-file-name: D:\my-trace.etl

    - name: Upload Trace
      uses: actions/upload-artifact@v4
      with:
        name: trace-${{ matrix.runs-on }}-${{ github.run_id }}
        path: D:\my-trace.etl